"""add_recipes

Revision ID: 7781e23eb274
Revises: a0752352a0e2
Create Date: 2024-03-16 00:30:05.939987

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7781e23eb274"
down_revision = "a0752352a0e2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("link", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recipes_name"), "recipes", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recipes_name"), table_name="recipes")
    op.drop_table("recipes")
    # ### end Alembic commands ###
